---
- name: Install extended services
  hosts: all
  become: true
  tasks:
    - name: Install MTA in web group
      yum:
        name: postfix
        state: latest
      when: inventory_hostname in groups["web"]
    - name: Install database in corresponding group
      yum:
        name: postgresql
        state: latest
      when: inventory_hostname in groups["database"]